### ISSUE TITLE
src/patreon-stream.ts:93:15 - error TS2739: Type 'ParsedQs' is missing the following properties from type 'FileUrlQS': h, i

### ISSUE THREAD

**Issue by ghost** [lavovaLampa/patreon-scraper#12]
I'm receiving the following error when trying to run the script on both the latest 64-bit NPM build on Windows, as well as when trying to run using npm on Ubuntu WSL:

```
TSError: ⨯ Unable to compile TypeScript:
src/patreon-stream.ts:93:15 - error TS2739: Type 'ParsedQs' is missing the following properties from type 'FileUrlQS': h, i

93         const result: FileUrlQS | null | undefined = qs.parse(qsPart)
                 ~~~~~~

    at createTSError (E:\Software\patreon-scraper\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (E:\Software\patreon-scraper\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (E:\Software\patreon-scraper\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (E:\Software\patreon-scraper\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (E:\Software\patreon-scraper\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (E:\Software\patreon-scraper\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
PS E:\Software\patreon-scraper>
```

Same error on both systems.

Linux system:
```
makoto@DESKTOP-1997FKK:/mnt/e/Software/patreon-scraper$ uname -a
Linux DESKTOP-1997FKK 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
makoto@DESKTOP-1997FKK:/mnt/e/Software/patreon-scraper$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
makoto@DESKTOP-1997FKK:/mnt/e/Software/patreon-scraper$
```

**Comment by pkwagner** [comment]
Did you maybe use `yarn` for installation? Just encountered the same problem, but using `npm` instead works fine for me.

**Comment by lavovaLampa** [comment]
The project has been refactored and re-written, this should now work.
